### ISSUE TITLE
add_row doesn't seem to work

### ISSUE THREAD

**Issue by solnic** [danmurphy1217/notion-ruby#17]
Hey there! Thanks for this gem. I just gave it a shot and unfortunately it seems like add_row doesn't really work. I'm getting a response from Notion with `PostgresNullConstraintError`. I have a basic collection with Name property and I do:

```ruby
page.add_row(Name: "Test")
```

I tried with different collections and different property names (ie `"Title"` or `"title"` but nothing works).

Am I doing something wrong or is it a bug?

**Comment by danmurphy1217** [comment]
Hello! I tried testing your code on a few Notion tables with the most recent Gem (1.0.5) and was not able to replicate the same error. Could you post some more info about the schema of your table? What property (column) types were you using? Is there only one property (column) or multiple?

Here's something you could try:
- `.add_row` was designed to accept a hash of property-value pairs. So, in your example, you'd do `.add_row({"Name" => "Test"})`. I tried both this and your approach and they worked for a few of my personal Notion tables, so I'm not sure if it will work for you.

Let me know!

**Comment by solnic** [comment]
@danmurphy1217 correct! I tested it out using existing collections

**Comment by danmurphy1217** [comment]
> @danmurphy1217 correct! I tested it out using existing collections

What version are you using? 1.0.5?

I tested with that version this AM and only ran into that issue when calling `.add_row` on a collection **immediately** after creating it (and I'm pretty sure this happens because Notion does not recognize the Collection ID yet). 

If you're not using 1.0.5 can you try updating the version? And if you are using 1.0.5 then let me know and I will dig into the code and try and replicate the error and push a fix today.

**Comment by solnic** [comment]
@danmurphy1217 I tried 1.0.5 and also current master. I also tried with different pages and different accounts. Thanks for your help!

**Comment by danmurphy1217** [comment]
Got it! I will try and replicate with 1.0.5 and push a fix ASAP. Probably tonight or tomorrow. 
> @danmurphy1217 I tried 1.0.5 and also current master. I also tried with different pages and different accounts. Thanks for your help!

**Comment by danmurphy1217** [comment]
@solnic Alright, I've made a few minor changes that should make the `.add_row` functionality better. But, I'm still unable to replicate the null constraint error:shrug:. If these changes do not solve the problem for any of your collection views, could you provide me with a bit more info? Some things that would be helpful:
1. the schema (property names) of the table,
2. the **types** of the properties? 
3. If you run into the error again, could you paste the output of the error here? It would be helpful to see what JSON is being sent to Notion.

Also, if you want to dig into the code yourself and try and get it working locally the method is defined on line 25 of the `collection_view_blocks.rb` file. Really appreciate your feedback!

Here's a few examples of the updates:
1. Passing column names out of order and as symbols now works correctly -> [Link](https://share.getcloudapp.com/z8u4xyDy)
2. Passing a specific column name works -> [Link](https://share.getcloudapp.com/YEuQ17Ko)

Changes are pushed as version 1.0.6. See #18!

**Comment by solnic** [comment]
@danmurphy1217 I managed to make it work WHEN I have a page that has another page as its parent that is a table. Then I can add rows. BUT, if I add a page and make it a table (so it has no parent), then it does not work. Hope this helps.

**Comment by danmurphy1217** [comment]
ahhh interesting, I did not even know you could create root tables. That's really helpful. I will push fix for that tonight.

**Comment by danmurphy1217** [comment]
#19, Hope this fixes things on your end!

**Comment by danmurphy1217** [comment]
@solnic, see #19 and #20. You should now be able to add rows on a root CV page, and you should also be able to work with any property type (select, multi-select, phone number, number, etc...). Let me know if there are any other features that would be helpful, and also let me know if you run into any problems.

**Comment by solnic** [comment]
@danmurphy1217 hey, it still doesn't work, furthermore - after trying out 1.0.7 my account is now crashing anytime I try to access anything that needs my task list :/

**Comment by solnic** [comment]
After some debugging it looks like the row was created with a null value, it definitely uncovered a bug on the notion side, unfortunately I can't tell which property it was :/ Another thing is that `collection_view_blocks.rb#L37` crashes when there's no sort set OR when there's no rows (I think).

When it comes to root-level database pages - how do you access them via `get_page`? It seems like this method only accepts URLs to "normal" pages at the moment.

**Comment by danmurphy1217** [comment]
Yes, this was fixed with the most recent version (1.1.0). It was when there are no options set for a select or multi-select column.
> After some debugging it looks like the row was created with a null value, it definitely uncovered a bug on the notion side, unfortunately I can't tell which property it was :/ Another thing is that `collection_view_blocks.rb#L37` crashes when there's no sort set OR when there's no rows (I think).


Currently, the best way to get them is to pass the ID straight to the method but I'll try and solve for this in the next update too.
> When it comes to root-level database pages - how do you access them via `get_page`? It seems like this method only accepts URLs to "normal" pages at the moment.

**Comment by solnic** [comment]
Thank you! Which ID are you talking about? There's page id and then there's view id.

**Comment by danmurphy1217** [comment]
> @danmurphy1217 hey, it still doesn't work, furthermore - after trying out 1.0.7 my account is now crashing anytime I try to access anything that needs my task list :/

What specifically is not working? With 1.1.0, you should be able to use `.add_row` successfully with any property type. If you are not able to read data using `.<property_name>`, that's probably a different issue. Oddly, I've been able to do that with the most up-to-date gem successfully for select and multi-select properties.


> Thank you! Which ID are you talking about? There's page id and then there's view id.

<img width="756" alt="Screen Shot 2020-12-06 at 6 12 41 AM" src="https://user-images.githubusercontent.com/48813027/101278565-10b14680-378a-11eb-9134-5262dba318df.png">
In this image, it's the one in between the `forward slash` and the `?` (3a38C...)

**Comment by danmurphy1217** [comment]
@solnic I added support for retrieving a collection view page directly with the full URL #22. I also pushed a few other changes so that when you add a row, you can read the column attributes from that row directly after it was created (before, you'd have to retrieve that row separately). I'm not sure if this will fix your specific problem,  but if you want to test it out that would be helpful.

I'm not gonna push a new version of the gem until we resolve this issue, so if you wanna test it out just pull the latest from the master branch.

**Comment by solnic** [comment]
@danmurphy1217 sorry, but still no go with getting a collection page via ID - get_page returns an empty hash for me when I do `client.get_page(my_collection_page_id)`

**Comment by danmurphy1217** [comment]
@solnic:
 
That's likely to mean you don't have the correct or any notion `token_v2` set. Alternatively, you may have to set an active user header (especially if you have different notion accounts). 

See the troubleshooting section [here](https://github.com/danmurphy1217/notion-ruby#troubleshooting).

Also, in an effort to close this issue, I want to check the status of the problems you've run into:

1. `.add_row` did not work on a root Collection View page. This should now be addressed and working correctly.
2. `.get_page` would not work with a URL for a collection view page. This should also be addressed and correctly working.

If these problems are not solved (or if there are any others), could you post:
-  the code you ran that led to the error
- the expected/desired functionality
- the error

**Comment by solnic** [comment]
Yes this can be closed. `.add_row` does work but I cannot access a top-level database page with URL or ID:

```
(byebug) page = client.get_page("https://www.notion.so/solnictest/d8c90c16041340a29640afab5799d3a7?v=86ddf373761d44a7a3b8a92f6d1b86d2")
*** RuntimeError Exception: the URL or ID passed to the get_page method must be that of a Page Block.

(byebug) page = client.get_page("d8c90c16041340a29640afab5799d3a7")
*** RuntimeError Exception: the URL or ID passed to the get_page method must be that of a Page Block.
```

I triple-checked the token and I also tried with and without `x-notion-active-user-header`.

**Comment by danmurphy1217** [comment]
Hi @solnic, I assume you were testing this with the gem. I have not yet pushed those changes as a new gem version yet (see [here](https://github.com/danmurphy1217/notion-ruby/issues/17#issuecomment-739497549) ), I wanted to make sure I was fixing your issues beforehand. I will push all changes as a new version now.

**Comment by solnic** [comment]
@danmurphy1217 hmm I'm pretty sure I checked using latest master

**Comment by danmurphy1217** [comment]
> @danmurphy1217 hmm I'm pretty sure I checked using latest master

I tested with the gem and with the master branch and the master branch worked but the gem did not. I'm pretty confident that this latest gem version (being pushed in a minute or two) will fix that problem but if not let's open up a new issue.

**Comment by solnic** [comment]
@danmurphy1217 thanks! I created a new task page and it worked with that page, it still doesn't work the original one I used for testing but I'm gonna let it go because it's not important, maybe it's some weird caching issue.
